# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93c072cf33f39a4a8b20ce7e82984b38"
name = "Product_Manager_Pro"
application_url = "https://particularly-attach-spyware-achieving.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_inventory,read_locations,read_publications,write_products"

[auth]
redirect_urls = [
  "https://particularly-attach-spyware-achieving.trycloudflare.com/api/auth",
  "https://particularly-attach-spyware-achieving.trycloudflare.com/api/auth/callback"
]
